version: '3'

services:
  pokemon-api:
    container_name: pokemon-api
    build: '.'
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - pokemon-mongodb
    networks:
      - app-connect
    links:
      - pokemon-mongodb
    ports:
      - '3333:3333'

  pokemon-mongodb:
    container_name: pokemon-mongodb
    image: mongo
    restart: unless-stopped
    env_file: .env
    volumes:
      - pokemon-mongodb-data:/data
    environment:
      MONGO_DB: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    networks:
      - app-connect
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'

volumes:
  pokemon-mongodb-data:

networks:
  app-connect:
    driver: bridge
